In [6]:
#The Scenario: You act as junior seismologists analyzing recent global earthquake data.
#Data Structures: You separate out specific columns, like the magnitude, to see how it behaves as an isolated 1D Series compared to the 2D DataFrame context.
import pandas as pd
df = pd.read_csv("earthquake - earthquake.csv")
print(df)
df['mag']
df[['mag','place', 'magSource']]

                         time   latitude   longitude    depth   mag magType  \
0    2026-03-10T06:28:05.052Z  37.448900  140.995500   69.630  4.60      mb
1    2026-03-10T06:09:51.071Z  62.340000 -151.493000   97.800  2.60      ml
2    2026-03-10T05:52:01.570Z  42.145333 -120.967167    6.890  3.25      ml
3    2026-03-10T05:20:04.300Z -23.345500  171.564500   10.000  5.00      mb
4    2026-03-10T04:46:26.147Z  61.808000 -148.696000   19.300  3.60      ml
..                        ...        ...         ...      ...   ...     ...
432  2026-03-03T02:12:10.368Z  54.253600 -162.330400   17.504  2.60      ml
433  2026-03-03T02:04:04.032Z  53.980900 -163.751600   33.218  2.70      ml
434  2026-03-03T01:40:34.692Z  52.407400 -170.018200   21.445  3.00      ml
435  2026-03-03T00:23:40.452Z  58.337000 -155.067000  114.600  2.90      ml
436  2026-03-03T00:11:43.467Z  25.289300  124.890600   10.000  5.00     mww

     nst  gap    dmin   rms  ...                   updated  \
0     57   94  2.4100  0.78  ...  2026-03-10T06:55:58.040Z
1     51   60  0.4000  0.60  ...  2026-03-10T07:27:39.040Z
2      8   83  0.2554  0.09  ...  2026-03-10T07:22:18.082Z
3     50  127  3.8640  0.78  ...  2026-03-10T05:38:31.040Z
4    170   29  0.1000  1.20  ...  2026-03-10T08:05:51.269Z
..   ...  ...     ...   ...  ...                       ...
432   14  219  0.7190  0.72  ...  2026-03-03T02:33:34.040Z
433   20  217  0.6650  0.87  ...  2026-03-03T02:14:06.040Z
434   13  305  0.3910  0.41  ...  2026-03-03T02:09:09.040Z
435  109   43  0.0000  0.60  ...  2026-03-03T04:59:51.040Z
436   67   91  1.0840  0.50  ...  2026-03-03T04:53:04.040Z

                                place        type horizontalError depthError  \
0              3 km S of Namie, Japan  earthquake            3.08     6.9340
1         39 km N of Skwentna, Alaska  earthquake            3.40     3.3504
2          36 km E of Bonanza, Oregon  earthquake            0.31     0.9400
3    southeast of the Loyalty Islands  earthquake           10.17     1.9250
4    4 km NE of Sutton-Alpine, Alaska  earthquake            1.60     1.4125
..                                ...         ...             ...        ...
432      89 km S of King Cove, Alaska  earthquake            5.72    12.7950
433   99 km SSW of False Pass, Alaska  earthquake            4.16    14.0810
434      98 km SW of Nikolski, Alaska  earthquake           12.05    18.0880
435       92 km NNW of Karluk, Alaska  earthquake            3.80     1.3154
436         67 km NW of Hirara, Japan  earthquake            5.65     1.7730

     magError  magNst     status  locationSource magSource
0    0.054000   104.0   reviewed              us        us
1    0.100000     4.0  automatic              ak        ak
2    0.142146    24.0   reviewed              uw        uw
3    0.071000    64.0   reviewed              us        us
4    0.200000    24.0  automatic              ak        ak
..        ...     ...        ...             ...       ...
432  0.115000    10.0   reviewed              us        us
433  0.115000    10.0   reviewed              us        us
434  0.105000    12.0   reviewed              us        us
435  0.400000    79.0   reviewed              ak        ak
436  0.066000    22.0   reviewed              us        us

[437 rows x 22 columns]

      mag                             place magSource
0    4.60            3 km S of Namie, Japan        us
1    2.60       39 km N of Skwentna, Alaska        ak
2    3.25        36 km E of Bonanza, Oregon        uw
3    5.00  southeast of the Loyalty Islands        us
4    3.60  4 km NE of Sutton-Alpine, Alaska        ak
..    ...                               ...       ...
432  2.60      89 km S of King Cove, Alaska        us
433  2.70   99 km SSW of False Pass, Alaska        us
434  3.00      98 km SW of Nikolski, Alaska        us
435  2.90       92 km NNW of Karluk, Alaska        ak
436  5.00         67 km NW of Hirara, Japan        us

[437 rows x 3 columns]

In [7]:
#Data I/O: You start by loading the data using pd.read_csv(). Later, you will export their filtered findings using .to_excel() or .to_json() for a web team to use.
df.to_csv("Mom_earthquake.xlsx")
print(f"File saved successful")

File saved successful

In [8]:
#Initial Data Inspection: Before doing anything, you must run .info() and .describe() to understand the sheer volume of data, use .head() to see the layout, and use .value_counts() to see which regions have the most frequent seismic activity.
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 437 entries, 0 to 436
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   time             437 non-null    object
 1   latitude         437 non-null    float64
 2   longitude        437 non-null    float64
 3   depth            437 non-null    float64
 4   mag              437 non-null    float64
 5   magType          437 non-null    object
 6   nst              437 non-null    int64
 7   gap              437 non-null    int64
 8   dmin             435 non-null    float64
 9   rms              437 non-null    float64
 10  net              437 non-null    object
 11  id               437 non-null    object
 12  updated          437 non-null    object
 13  place            437 non-null    object
 14  type             437 non-null    object
 15  horizontalError  427 non-null    float64
 16  depthError       437 non-null    float64
 17  magError         434 non-null    float64
 18  magNst           435 non-null    float64
 19  status           437 non-null    object
 20  locationSource   437 non-null    object
 21  magSource        437 non-null    object
dtypes: float64(10), int64(2), object(10)
memory usage: 75.2+ KB

,latitude,longitude,depth,mag,nst,gap,dmin,rms,horizontalError,depthError,magError,magNst
count,437.000000,437.000000,437.000000,437.000000,437.000000,437.000000,435.000000,437.000000,427.000000,437.000000,434.000000,435.000000
mean,34.776555,-37.736996,50.419789,3.663249,47.750572,139.059497,1.624267,0.655337,6.980475,4.472189,0.121309,43.450575
std,26.430813,134.684577,99.165012,0.989571,38.852397,79.240235,3.606685,0.303047,5.858383,4.346007,0.076124,57.204212
min,-59.386800,-179.980800,-1.530000,2.500000,5.000000,14.000000,0.000000,0.070200,0.070000,0.000000,0.008535,3.000000
25%,19.420500,-155.221500,10.000000,2.720000,20.000000,70.000000,0.357500,0.450000,2.800000,1.874000,0.073000,13.000000
50%,43.549200,-93.414700,11.086000,3.300000,37.000000,130.000000,0.734000,0.680000,6.100000,2.536000,0.100000,25.000000
75%,52.404000,125.381900,43.102000,4.500000,59.000000,201.000000,1.472000,0.870000,9.575000,6.487200,0.148000,52.500000
max,73.227100,179.979500,618.136000,6.400000,236.000000,322.000000,46.843000,1.450000,57.400000,31.610000,0.500000,663.000000

In [9]:
df.head(2)

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
0,2026-03-10T06:28:05.052Z,37.4489,140.9955,69.63,4.6,mb,57,94,2.41,0.78,...,2026-03-10T06:55:58.040Z,"3 km S of Namie, Japan",earthquake,3.08,6.9340,0.054,104.0,reviewed,us,us
1,2026-03-10T06:09:51.071Z,62.3400,-151.4930,97.80,2.6,ml,51,60,0.40,0.60,...,2026-03-10T07:27:39.040Z,"39 km N of Skwentna, Alaska",earthquake,3.40,3.3504,0.100,4.0,automatic,ak,ak

In [10]:
df["country"] = df["place"].str.split(",").str[-1].str.strip()
df['country'].value_counts()

country
Alaska                              195
Russia                               21
Puerto Rico                          16
New Mexico                           16
CA                                   15
                                   ...
Greece                                1
Bouvet Island region                  1
Colombia                              1
southeast of the Loyalty Islands      1
Croatia                               1
Name: count, Length: 64, dtype: int64

In [11]:
#Column/Label/Integer: Use dictionary-style selection to grab the 'Location' column. Use .iloc[] to extract the top 5 largest earthquakes based on row position.
location = df['locationSource']
print(location)
df["country"] = df["place"].str.split(",").str[-1].str.strip()
abc_df = df.sort_values(by='country', ascending=False)

top5 = abc_df.iloc[0:5]['country']
print(top5)

0      us
1      ak
2      uw
3      us
4      ak
       ..
432    us
433    us
434    us
435    ak
436    us
Name: locationSource, Length: 437, dtype: object
3      southeast of the Loyalty Islands
13            south of the Fiji Islands
238           south of the Fiji Islands
21            south of the Fiji Islands
323           south of the Fiji Islands
Name: country, dtype: object

#Filtering: Apply multiple boolean conditions using & and | to find earthquakes that are both greater than magnitude 6.0 and occurred in a specific region (e.g., "Japan" or “Texas”).

In [12]:
df["country"] = df["place"].str.split(",").str[-1].str.strip()
bool_greater_than_6and_japan = (df['mag']> 6.0) & (df['country']=='Japan')
greater_than_6and_japan = df[bool_greater_than_6and_japan][['mag', 'country']]
print(greater_than_6and_japan)

Empty DataFrame
Columns: [mag, country]
Index: []

In [13]:

df["country"] = df["place"].str.split(",").str[-1].str.strip()
bool_greater_than_6and_japan = (df['mag']> 6.0) | (df['country']=='Japan')
greater_than_6and_japan = df[bool_greater_than_6and_japan][['mag', 'country']]
print(greater_than_6and_japan)

     mag          country
0    4.6            Japan
19   4.7            Japan
20   4.4            Japan
31   5.9            Japan
38   4.1            Japan
94   5.7            Japan
95   5.4            Japan
200  4.9            Japan
207  4.8            Japan
228  6.3  Solomon Islands
270  4.6            Japan
284  4.8            Japan
304  5.2            Japan
341  6.4           Alaska
386  4.7            Japan
428  6.2        Indonesia
436  5.0            Japan